# Configuration for Rasa NLU and Core components
recipe: default.v1
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default"
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
  - name: TEDPolicy
    max_history: 10
    epochs: 100
    constrain_similarities: true

assistant_id: "medical-assistant-chatbot"

tracker_store:
  type: InMemoryTrackerStore
  url: postgresql://user:password@localhost:5432/rasa_db
  db: rasa
  username: postgres
  password: password
  dialect: postgresql

lock_store:
  type: InMemoryLockStore

endpoints:
  action_endpoint:
    url: http://localhost:5055/webhook